"""add gitea_username to user model

Revision ID: 08a73307418d
Revises: ecc7c0ff0957
Create Date: 2026-01-05 13:36:16.845876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a73307418d'
down_revision = 'ecc7c0ff0957'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gitea_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gitea_username')
    # ### end Alembic commands ###






